### ISSUE TITLE
Analysis Discussion

### ISSUE THREAD

**Issue by agill59** [DSCI-310-2024/DSCI-310_predicting-shares_group-4#7]
summarize what you found
discuss whether this is what you expected to find?
discuss what impact could such findings have?
discuss what future questions could this lead to?

**Comment by anshnoorkaur** [comment]
Are we using all variables available in the dataset as predictors? If so, would it be better to select a few to obtain more useful results and make the analysis question more specific? I would suggest number of images, number of videos, and number of words in the content. What does everyone think?

**Comment by anshnoorkaur** [comment]
Analysis file is still missing the following: Numbers and legends for figures and tables, text in the ending discussion and references section.

Also loading data needs to be updated since we need to load data from the original source on the web according to the assignment details and not the data folder like we're currently doing. Here is some guidance for doing so:
url <- "datafile-url-here"
data <- read_csv(url,
                       col_names = c("colour", "petal_length", 
                                      "is_small" )) |> # Add column names to the data frame.
